### ISSUE TITLE
Integration Issue : SpeechRecognizer already active

### ISSUE THREAD

**Issue by anirudhjain75** [sljavi/handsfree-for-website#4]
I tried following the readme file with this repo to integrate handsfree tools with my website. I'm using a react website and the exact error is `DOMException: Failed to execute 'start' on 'SpeechRecognition': recognition has already started.`

Operating System: Mac OS Big Sur
Browser: Chrome 83.0.4103.116

**Comment by sljavi** [comment]
Hi @anirudhjain75 could you share the code you're using to initialize lib? Any chance the `init` or `turnOn` methods are executed more than once?

**Comment by anirudhjain75** [comment]
No the code aren't being executed more than once

**Comment by anirudhjain75** [comment]
```hansfreeForWebsite.init({
      turnedOn: true,
      continuesRecognition: true
    });```

**Comment by anirudhjain75** [comment]
hansfreeForWebsite.init({
      turnedOn: true,
      continuesRecognition: true
    });

**Comment by anirudhjain75** [comment]
> Hi @anirudhjain75 could you share the code you're using to initialize lib? Any chance the `init` or `turnOn` methods are executed more than once?

Thanks I just made a change so its confirmed to be executed only once. Its a great tool

**Comment by sljavi** [comment]
thanks @anirudhjain75 
if the project you're working on gets published could you share it? It will be great to reference it as an example.

**Comment by anirudhjain75** [comment]
Sure
